// ============================================
// CURRICULUM DATA — Efficient AI PhD Tracker
// ============================================
const PHASES = [
  {id:"1A",year:1,title:"Mathematics",months:"1–4",color:"#818cf8"},
  {id:"1B",year:1,title:"Systems: C/C++ & Hardware",months:"4–8",color:"#6366f1"},
  {id:"1C",year:1,title:"Deep Learning Foundations",months:"8–12",color:"#a78bfa"},
  {id:"2A",year:2,title:"Quantization",months:"13–18",color:"#34d399"},
  {id:"2B",year:2,title:"Pruning",months:"16–20",color:"#2dd4bf"},
  {id:"2C",year:2,title:"Knowledge Distillation",months:"19–22",color:"#14b8a6"},
  {id:"2D",year:2,title:"Efficient Training",months:"21–23",color:"#0d9488"},
  {id:"2E",year:2,title:"Deployment",months:"23–24",color:"#059669"},
  {id:"3A",year:3,title:"Low-Rank & PEFT",months:"25–29",color:"#fb923c"},
  {id:"3B",year:3,title:"Mixture of Experts",months:"28–32",color:"#f97316"},
  {id:"3C",year:3,title:"State Space Models",months:"31–34",color:"#ea580c"},
  {id:"3D",year:3,title:"Attention & Spec. Decoding",months:"33–37",color:"#dc2626"},
  {id:"3E",year:3,title:"Training at Scale",months:"35–38",color:"#e11d48"},
  {id:"3F",year:3,title:"TinyML & Edge",months:"37–40",color:"#db2777"},
  {id:"4A",year:4,title:"Research Methodology",months:"41–44",color:"#f472b6"},
  {id:"4B",year:4,title:"Advanced Topics",months:"43–48",color:"#ec4899"},
  {id:"4C",year:4,title:"Original Research",months:"46–48+",color:"#d946ef"},
];

const PROJECTS = [
  {id:"1.1",phase:"1A",name:"SVD from scratch (NumPy eig() only)"},
  {id:"1.2",phase:"1A",name:"KL divergence explorer (visualize asymmetry)"},
  {id:"1.3",phase:"1A",name:"Scalar autograd engine (micrograd-style)"},
  {id:"1.4",phase:"1A",name:"Optimizer comparison (SGD vs Momentum vs Adam)"},
  {id:"1.5",phase:"1B",name:"Cache-aware matrix multiplication (3 versions in C)"},
  {id:"1.6",phase:"1B",name:"Memory allocator (free-list malloc/free in C)"},
  {id:"1.7",phase:"1B",name:"First HIP kernel (vec add + naive matmul)"},
  {id:"1.8",phase:"1B",name:"HIP tiled matrix multiply (shared memory / LDS)"},
  {id:"1.9",phase:"1C",name:"ResNet-18 from scratch (>90% CIFAR-10)"},
  {id:"1.10",phase:"1C",name:"Transformer from scratch (char-level GPT)"},
  {id:"1.11",phase:"1C",name:"Profiling baseline (PyTorch Profiler on AMD)"},
  {id:"2.1",phase:"2A",name:"Mixed-precision training baseline (AMP)"},
  {id:"2.2",phase:"2A",name:"PTQ from scratch (INT8 absmax + zero-point)"},
  {id:"2.3",phase:"2A",name:"QAT implementation (fake quant + STE)"},
  {id:"2.4",phase:"2A",name:"GPTQ reproduction (OBQ loop on char-GPT)"},
  {id:"2.5",phase:"2A",name:"Custom INT8 HIP kernel (int8×int8→int32)"},
  {id:"2.6",phase:"2B",name:"Unstructured magnitude pruning (90% sparse)"},
  {id:"2.7",phase:"2B",name:"Structured channel pruning (real removal)"},
  {id:"2.8",phase:"2B",name:"Lottery Ticket reproduction (LeNet-5)"},
  {id:"2.9",phase:"2B",name:"N:M sparsity experiment (2:4 structured)"},
  {id:"2.10",phase:"2C",name:"Classic temperature distillation (ResNet sweep)"},
  {id:"2.11",phase:"2C",name:"Feature-map distillation (FitNets-style)"},
  {id:"2.12",phase:"2C",name:"TinyBERT-style transformer distillation"},
  {id:"2.13",phase:"2D",name:"Gradient checkpointing (memory vs compute)"},
  {id:"2.14",phase:"2D",name:"torch.compile on AMD (benchmark)"},
  {id:"2.15",phase:"2D",name:"Distributed training setup (DDP)"},
  {id:"2.16",phase:"2E",name:"Full export pipeline (ONNX + MIGraphX)"},
  {id:"2.17",phase:"2E",name:"llama.cpp deep dive (ROCm build + analysis)"},
  {id:"2.18",phase:"2E",name:"Serving benchmark (vLLM on ROCm)"},
  {id:"3.1",phase:"3A",name:"LoRA from scratch (custom nn.Module)"},
  {id:"3.2",phase:"3A",name:"Rank sensitivity analysis (r sweep on BERT)"},
  {id:"3.3",phase:"3A",name:"SVD weight compression (truncated SVD)"},
  {id:"3.4",phase:"3A",name:"QLoRA on AMD (7B NF4 + LoRA)"},
  {id:"3.5",phase:"3B",name:"MoE FFN layer (top-2 gating + balancing)"},
  {id:"3.6",phase:"3B",name:"Expert collapse experiment"},
  {id:"3.7",phase:"3B",name:"MoE efficiency analysis (FLOPs vs latency)"},
  {id:"3.8",phase:"3C",name:"Mamba block implementation (selective scan)"},
  {id:"3.9",phase:"3C",name:"Inference benchmark — Mamba vs Transformer"},
  {id:"3.10",phase:"3C",name:"RWKV WKV kernel annotation"},
  {id:"3.11",phase:"3D",name:"⭐ FlashAttention tiling (HIP kernel)"},
  {id:"3.12",phase:"3D",name:"KV cache + GQA implementation"},
  {id:"3.13",phase:"3D",name:"Speculative decoding implementation"},
  {id:"3.14",phase:"3D",name:"Linformer approximation error analysis"},
  {id:"3.15",phase:"3E",name:"FSDP training (~350M model)"},
  {id:"3.16",phase:"3E",name:"DeepSpeed ZeRO (Stage 2+3)"},
  {id:"3.17",phase:"3E",name:"Scaling laws experiment (10M–200M)"},
  {id:"3.18",phase:"3F",name:"MobileNetV2 from scratch + TFLite"},
  {id:"3.19",phase:"3F",name:"MCU deployment (keyword spotting <256KB)"},
  {id:"3.20",phase:"3F",name:"NAS for MCU (Pareto frontier)"},
  {id:"4.1",phase:"4A",name:"⭐ Reproducibility study (within 5%)"},
  {id:"4.2",phase:"4A",name:"Literature graph (citation map + gaps)"},
  {id:"4.3",phase:"4A",name:"Conference-style peer review (3 papers)"},
  {id:"4.4",phase:"4B",name:"SparseGPT reproduction (OBS on OPT)"},
  {id:"4.5",phase:"4B",name:"PagedAttention implementation"},
  {id:"4.6",phase:"4B",name:"BitNet-style ternary training"},
  {id:"4.7",phase:"4B",name:"Model merging experiment (TIES/DARE)"},
  {id:"4.8",phase:"4C",name:"Research proposal (4-page doc)"},
  {id:"4.9",phase:"4C",name:"Experimental results + ablations"},
  {id:"4.10",phase:"4C",name:"Paper draft (conference format)"},
  {id:"4.11",phase:"4C",name:"Open-source release (code + weights)"},
];

const GATES = [
  {id:"1A",title:"Gate 1A — Mathematics (Month 4)", phase:"1A", items:[
    "Derive SVD from eigendecomposition; explain geometric meaning of U, Σ, Vᵀ",
    "Prove Frobenius norm = √(sum of squared singular values)",
    "Explain KL divergence asymmetry and implications for distillation loss direction",
    "Derive Adam update rule from first principles (moments + bias correction)",
    "Explain MLE vs MAP; give example where they differ; connect MAP to regularization",
    "State a concentration inequality (Hoeffding/Markov); explain relevance to generalization",
    "Derive gradient of softmax cross-entropy loss w.r.t. logits",
  ]},
  {id:"1B",title:"Gate 1B — Systems (Month 8)", phase:"1B", items:[
    "Explain L1/L2/L3 cache hierarchy; why tiled matmul improves cache utilization",
    "Predict cache miss rate of naive matmul; explain how blocking fixes it",
    "Write a HIP kernel from memory; explain thread blocks, wavefronts, coalescing",
    "Difference between wavefronts (AMD 64) and warps (NVIDIA 32)",
    "Describe AMD MI Max+ 395 memory hierarchy: HBM bandwidth, LDS, L1/L2 sizes",
    "Explain GPU occupancy and why higher isn't always better",
    "Why global memory accesses must be coalesced; what happens if not",
  ]},
  {id:"1C",title:"Gate 1C — Deep Learning (Month 12)", phase:"1C", items:[
    "Explain full forward/backward pass of transformer block including attention gradients",
    "Read profiler FLOP count + bandwidth; determine compute-bound vs memory-bound",
    "Explain why ResNets train better (gradient flow through skip connections)",
    "Difference between batch norm and layer norm; why transformers use layer norm",
    "Implement backprop for 3-layer MLP from scalar ops (on paper)",
    "Explain the roofline model; determine if operation is compute or memory bound",
  ]},
  {id:"2A",title:"Gate 2A — Quantization (Month 18)", phase:"2A", items:[
    "Symmetric vs asymmetric quantization — when is each preferred?",
    "Why per-channel quantization > per-tensor (dynamic range per channel)",
    "Outlier features in LLMs: what, why, how LLM.int8() handles them",
    "Derive STE gradient; explain why it works despite being mathematically incorrect",
    "Role of Hessian in GPTQ; greedy column-by-column update",
    "Loss scaling in mixed-precision; why FP16 needs it, BF16 often doesn't",
    "Calculate memory savings: INT8 vs FP16 vs FP32 for N parameters",
  ]},
  {id:"2B",title:"Gate 2B — Pruning (Month 20)", phase:"2B", items:[
    "Why unstructured sparsity rarely accelerates inference on GPUs",
    "Why structured pruning maps better to hardware",
    "Derive OBD saliency formula (2nd-order Taylor, diagonal Hessian)",
    "N:M structured sparsity: what it is, hardware speedup, supported hardware",
    "Lottery Ticket Hypothesis and rewinding procedure",
  ]},
  {id:"2C",title:"Gate 2C — Distillation (Month 22)", phase:"2C", items:[
    "Derive distillation gradient; why higher T produces richer signal",
    "Why temperature scaling works mathematically (softmax entropy vs T)",
    "Three failure modes of feature distillation with capacity mismatch",
    "Task-specific vs task-agnostic distillation with examples",
  ]},
  {id:"2D",title:"Gate 2D — Efficient Training (Month 23)", phase:"2D", items:[
    "Memory-compute tradeoff in gradient checkpointing",
    "What torch.compile does: graph capture, Triton lowering, operator fusion",
    "All-reduce operation: what it computes, why it bottlenecks, ring all-reduce",
  ]},
  {id:"2E",title:"Gate 2E — Deployment (Month 24)", phase:"2E", items:[
    "What is an ONNX graph; why inference engines rebuild computation graph",
    "What calibration means in INT8 inference pipelines",
    "How llama.cpp packs 4-bit weights in GGUF; dequantized matmul",
    "AMD MIGraphX vs NVIDIA TensorRT comparison",
  ]},
  {id:"3A",title:"Gate 3A — Low-Rank & PEFT (Month 29)", phase:"3A", items:[
    "Prove B=0 init in LoRA → model starts identical to pretrained",
    "LoRA (additive low-rank) vs SVD weight decomposition (post-hoc)",
    "Intrinsic dimensionality hypothesis + supporting evidence",
    "QLoRA NF4: what is Normal Float; why info-theoretically optimal",
  ]},
  {id:"3B",title:"Gate 3B — MoE (Month 32)", phase:"3B", items:[
    "Expert collapse: cause, aux loss solution, too-high coefficient effects",
    "Why MoE models are memory-bound despite low active FLOPs",
    "Top-k routing vs expert-choice routing tradeoffs",
    "How Mixtral achieves 70B quality at 12B active params",
  ]},
  {id:"3C",title:"Gate 3C — State Space Models (Month 34)", phase:"3C", items:[
    "Why selective scan in Mamba ≠ standard convolution",
    "Hardware-aware parallel scan: what and why for GPU efficiency",
    "Mamba vs Transformer asymptotic complexity: training + inference",
    "HiPPO framework: problem solved, long-range dependency help",
  ]},
  {id:"3D",title:"Gate 3D — Attention & Spec. Decoding (Month 37)", phase:"3D", items:[
    "Why standard attention = O(N²) memory; FlashAttention online softmax avoids it",
    "IO bottleneck FlashAttention addresses (HBM reads/writes, not FLOPs)",
    "How speculative decoding guarantees exact output distribution",
    "Draft quality (acceptance rate α) vs speculative decoding speedup",
    "GQA: why standard over MHA/MQA; KV cache reduction",
  ]},
  {id:"3E",title:"Gate 3E — Training at Scale (Month 38)", phase:"3E", items:[
    "Three ZeRO stages: what each partitions",
    "FSDP vs DeepSpeed ZeRO: implementation diffs, AMD tradeoffs",
    "Chinchilla scaling law and its implication",
    "Tensor parallelism vs pipeline parallelism",
  ]},
  {id:"3F",title:"Gate 3F — TinyML (Month 40)", phase:"3F", items:[
    "MCU memory budget: activations (RAM) vs weights (flash) vs code (flash)",
    "Depthwise separable convolutions: decomposition, ~k² compute reduction",
    "Once-for-All: avoid per-target training (progressive shrinking)",
    "NAS search space design: dimensions searched, cost management",
  ]},
  {id:"4A",title:"Gate 4A — Research Methodology (Month 44)", phase:"4A", items:[
    "Reproduce a published paper's main result within 5%",
    "Identify a non-trivial open problem with evidence",
    "Write a formal peer review in NeurIPS format",
  ]},
  {id:"4B",title:"Gate 4B — Advanced Topics (Month 48)", phase:"4B", items:[
    "SparseGPT OBS-based pruning: why it works without retraining",
    "PagedAttention: KV cache as virtual memory → serving throughput",
    "BitNet b1.58: ternary-weight training implications for hardware",
  ]},
  {id:"4C",title:"Gate 4C — Original Research (Month 48+)", phase:"4C", items:[
    "Write a complete paper draft in conference format (8+ pages)",
    "Release reproducible code others can run and verify",
    "Present your work and defend against critical questions",
  ]},
];

const READING = [
  {section:"Textbooks — Mathematics",type:"textbook",items:[
    {pri:"critical",text:"Linear Algebra Done Right — Axler"},
    {pri:"reference",text:"The Matrix Cookbook — Petersen & Pedersen"},
    {pri:"critical",text:"Information Theory, Inference, and Learning Algorithms — MacKay (Ch.1–10)"},
    {pri:"critical",text:"Mathematics for Machine Learning — Deisenroth et al. (Ch.2–7)"},
    {pri:"important",text:"Convex Optimization — Boyd & Vandenberghe (Ch.1–4, 9)"},
  ]},
  {section:"Textbooks — Systems",type:"textbook",items:[
    {pri:"critical",text:"Computer Systems: A Programmer's Perspective — Bryant (Ch.1,5,6,9,12)"},
    {pri:"critical",text:"C Programming Language — K&R (cover to cover)"},
    {pri:"critical",text:"AMD ROCm & HIP Programming Guide"},
    {pri:"important",text:"Programming Massively Parallel Processors — Kirk & Hwu"},
  ]},
  {section:"Textbooks — Deep Learning",type:"textbook",items:[
    {pri:"important",text:"Deep Learning — Goodfellow et al. (Ch.6–11)"},
    {pri:"important",text:"Dive into Deep Learning — d2l.ai"},
  ]},
  {section:"Textbooks — TinyML & Research",type:"textbook",items:[
    {pri:"critical",text:"TinyML — Warden & Situnayake"},
    {pri:"important",text:"Writing for Computer Science — Zobel"},
    {pri:"important",text:"The Craft of Research — Booth et al."},
  ]},
  {section:"Papers — Foundations",type:"paper",items:[
    {pri:"important",text:"Shannon (1948) — A Mathematical Theory of Communication"},
    {pri:"important",text:"Kingma & Ba (2014) — Adam optimizer"},
    {pri:"critical",text:"He et al. (2015) — Deep Residual Learning (ResNet)"},
    {pri:"critical",text:"Vaswani et al. (2017) — Attention Is All You Need"},
    {pri:"important",text:"Brown et al. (2020) — GPT-3"},
    {pri:"critical",text:"Hennessy & Patterson (2019) — New Golden Age (Turing Lecture)"},
  ]},
  {section:"Papers — Quantization",type:"paper",items:[
    {pri:"critical",text:"Micikevicius et al. (2017) — Mixed Precision Training"},
    {pri:"critical",text:"Jacob et al. (2018) — Quantization and Training of NNs"},
    {pri:"critical",text:"Dettmers et al. (2022) — LLM.int8()"},
    {pri:"critical",text:"Frantar et al. (2022) — GPTQ"},
    {pri:"critical",text:"Lin et al. (2023) — AWQ"},
    {pri:"important",text:"Xiao et al. (2022) — SmoothQuant"},
    {pri:"critical",text:"Gholami et al. (2021) — Quantization Survey"},
  ]},
  {section:"Papers — Pruning",type:"paper",items:[
    {pri:"critical",text:"LeCun et al. (1990) — Optimal Brain Damage"},
    {pri:"critical",text:"Han et al. (2015) — Deep Compression"},
    {pri:"critical",text:"Frankle & Carlin (2018) — Lottery Ticket Hypothesis"},
    {pri:"important",text:"NVIDIA (2021) — 2:4 Structured Sparsity"},
    {pri:"important",text:"Zhu & Gupta (2017) — To Prune, or Not to Prune"},
  ]},
  {section:"Papers — Distillation",type:"paper",items:[
    {pri:"critical",text:"Hinton et al. (2015) — Distilling the Knowledge in a NN"},
    {pri:"critical",text:"Jiao et al. (2019) — TinyBERT"},
    {pri:"important",text:"Sanh et al. (2019) — DistilBERT"},
    {pri:"important",text:"Touvron et al. (2020) — DeiT"},
  ]},
  {section:"Papers — PEFT & LoRA",type:"paper",items:[
    {pri:"critical",text:"Hu et al. (2021) — LoRA"},
    {pri:"critical",text:"Dettmers et al. (2023) — QLoRA"},
    {pri:"important",text:"Aghajanyan et al. (2020) — Intrinsic Dimensionality"},
    {pri:"important",text:"Zhao et al. (2024) — GaLore"},
  ]},
  {section:"Papers — MoE & SSMs",type:"paper",items:[
    {pri:"critical",text:"Shazeer et al. (2017) — Sparsely-Gated MoE"},
    {pri:"critical",text:"Fedus et al. (2021) — Switch Transformers"},
    {pri:"critical",text:"Jiang et al. (2024) — Mixtral"},
    {pri:"critical",text:"Gu et al. (2021) — S4"},
    {pri:"critical",text:"Gu & Dao (2023) — Mamba"},
    {pri:"important",text:"Peng et al. (2023) — RWKV"},
  ]},
  {section:"Papers — Attention & Decoding",type:"paper",items:[
    {pri:"critical",text:"Dao et al. (2022) — FlashAttention"},
    {pri:"important",text:"Dao et al. (2023) — FlashAttention-2"},
    {pri:"critical",text:"Ainslie et al. (2023) — GQA"},
    {pri:"critical",text:"Leviathan et al. (2023) — Speculative Decoding"},
    {pri:"critical",text:"Kwon et al. (2023) — PagedAttention / vLLM"},
  ]},
  {section:"Papers — Scaling & Training",type:"paper",items:[
    {pri:"critical",text:"Rajbhandari et al. (2020) — ZeRO"},
    {pri:"critical",text:"Hoffmann et al. (2022) — Chinchilla Scaling Laws"},
    {pri:"important",text:"Narayanan et al. (2021) — Megatron-LM"},
  ]},
  {section:"Papers — Cutting Edge (Year 4)",type:"paper",items:[
    {pri:"critical",text:"Frantar & Alistarh (2023) — SparseGPT"},
    {pri:"critical",text:"Ma et al. (2024) — BitNet b1.58"},
    {pri:"important",text:"Yadav et al. (2024) — TIES-Merging"},
    {pri:"important",text:"Yu et al. (2024) — DARE"},
    {pri:"important",text:"Wortsman et al. (2022) — Model Soups"},
    {pri:"critical",text:"Wan et al. (2023) — Efficient LLMs Survey"},
  ]},
];

const YEAR_COLORS = {1:"#818cf8",2:"#34d399",3:"#fb923c",4:"#f472b6"};
